# -*- coding: utf-8 -*-
"""marble ai .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16BObDwd57G6pboSnbjihzuG11HW-vK8w

# to make mask for the intial product
"""

import cv2
import numpy as np
shoe_photo_path = "/content/product_image1.jpg"
shoe_photo = cv2.imread(shoe_photo_path)
gray = cv2.cvtColor(shoe_photo, cv2.COLOR_BGR2GRAY)
_, mask = cv2.threshold(gray, 240, 255, cv2.THRESH_BINARY)
mask = cv2.bitwise_not(mask)
mask = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)
shoe_photo_with_transparent_bg = np.where(mask == 255, 0, shoe_photo)
cv2.imwrite("imagewit5.png", shoe_photo_with_transparent_bg)

"""# **Adding the model using hugging face diffusers**"""

import torch
from diffusers import AutoPipelineForInpainting
from diffusers.utils import load_image, make_image_grid

pipeline = AutoPipelineForInpainting.from_pretrained(
    "kandinsky-community/kandinsky-2-2-decoder-inpaint", torch_dtype=torch.float16
)
pipeline.enable_model_cpu_offload()
# remove following line if xFormers is not installed or you have PyTorch 2.0 or higher installed
pipeline.enable_xformers_memory_efficient_attention()

init_image = load_image("/content/product_image1.jpg")
mask_image = load_image("/content/imagewit5.png")

"""#**prompt and adding the background for non masked parts**"""

prompt = "A photorealistic image of a luxurious shaving experience. A rich lather of shaving soap rests in a ceramic bowl beside a polished straight razor and a badger-hair shaving brush. Subtle steam rises, and natural light illuminates a marble countertop in a sophisticated bathroom setting,8k"
negative_prompt = "bad anatomy, deformed, ugly, disfigured"
image = pipeline(prompt=prompt, negative_prompt=negative_prompt, image=init_image, mask_image=mask_image).images[0]
image.save("shoe_final_image2.jpg")

"""#**prompts that i had used **"""

A photorealistic image of the brown leather loafers displayed on a plush, velvet platform within a luxurious retail store. High-end designer clothing hangs neatly on racks in the background. Spotlights illuminate the shoes, creating a dramatic effect
A photorealistic close-up of the brown leather loafers resting on a sleek, modern glass desk in a brightly lit office. Skyscrapers are visible through a large window in the background. Sunlight streams through the window, casting a warm glow on the shoes.
A photorealistic image of a pair of brown leather loafers resting on a natural stone walkway. The background is blurred greenery, suggesting a park or outdoor setting. The focus remains on the shoes.
A photorealistic image of the aftershave bottle displayed on a vintage wooden shelf in an old-fashioned barbershop. Leather barber chairs, shaving tools, and framed photographs line the background for a nostalgic feel
A photorealistic image of the aftershave bottle placed on a leather-bound book in a dimly lit study. A globe, antique pen, and a glass of whiskey are subtly visible in the background.
A photorealistic image of the aftershave bottle alongside a tailors measuring tape, fabric swatches, and a mannequin in a custom tailor shop. The setting evokes a sense of elegance and refinement.
A photorealistic image of the aftershave bottle displayed on a vintage wooden shelf in an old-fashioned barbershop. Leather barber chairs, shaving tools, and framed photographs line the background for a nostalgic feel.
A photorealistic close-up of the aftershave bottle on a marble countertop in a luxurious bathroom. A sleek shaving brush, a high-end watch, and folded towels create a sophisticated setting."
A photorealistic close-up of the ring resting on a plush, deep red velvet cushion. Soft, diffused light highlights the rings brilliance and the luxurious texture of the fabric.
A photorealistic image of the ring placed on a bed of velvety rose petals,Soft, filtered light creates a romantic atmosphere,8k
A photorealistic image of the ring nestled in the sand on a beach at sunset,soft waves and a breathtaking warm glow, romantic and dreamy setting,8k
A photorealistic image of a ring displayed on a velvet pedestal in a luxurious jewelry boutique. Light rays stream through a large window, illuminating the ring. Glass cases filled with other precious jewels are visible in the blurred background
A photorealistic image of a ring displayed in a jewelry shop. Light rays stream through a window, casting a warm spotlight on the ring and highlighting its brilliance
A photorealistic image of a natural shaving soap resting on wooden table which has placed in a forest while some of the sun rays falling on the table ,8k
A photorealistic image of a natural shaving soap resting on wooden table which has placed in a shop people were in the shop where there is no sun light at all its all night the tubelight rays was falling on the table  ,8k